### ISSUE TITLE
Shorten the sessions

### ISSUE THREAD

**Issue by dbosk** [OpenSecEd/ism#1]
Perhaps it's good to change from 2\times 45 minutes to independent 45-minute sessions?  At least so that it's 45 minutes of talking and the rest is discussion.

**Comment by lenfra** [comment]
> Perhaps it's good to change from 2\times 45 minutes to independent 45-minute sessions? At least so that it's 45 minutes of talking and the rest is discussion.

Closing this one and add it to the Active Learning issue, since they are related.
